theme = "modern"
icons = "awesome"

#[[block]]
#block = "custom"
#command = "$HOME/.config/i3status-rust/scripts/ShowMediaMeta.sh"
#interval = 1

[[block]] 
block = "music"
player = "mpd"
max_width = 22
marquee = true
buttons = ["prev", "play", "next"]

[[block]] 
block = "custom" 
command = "sed 's/  //' <(curl 'https://wttr.in/?format=1' -s)" 
interval = 600

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

#[[block]]
#block = "memory"
#display_type = "memory"
#format_mem = "{mem_used_percents}"
#format_swap = "{swap_used_percents}"

#[[block]]
#block = "load"
#interval = 1
#format = "{1m}"

#[[block]]
#block = "temperature"
#collapsed = false
#interval = 10
#format = "{average}C (CPU)"


[[block]] 
block = "sound" 
driver = "pulseaudio" 
on_click = "pavucontrol" 
step_width = 5 
show_volume_when_muted = true

#[[block]] 
#block = "backlight"

#[[block]]
#block = "cpu"
#interval = 1

[[block]]
block = "battery"
if_command = "test -e /sys/class/power_supply/BAT0"

[[block]]
block = "time"
interval = 5
format = "%m/%d %r"

